Provide feature to compare repo with specific branch and tag.
garrowsmith/site-studio-compare pull request #3
Opened 2021-05-18 08:15 UTC by rakshithtb

Provide feature to compare repo with specific branch and tag.

2021-06-02 11:17 UTC, garrowsmith requested changes
Provided review comments, would like some addition to Readme.md or a PackageRepo.md to detail any setup or examples.

2021-06-02 11:17 UTC, garrowsmith commented on src/Package/ComparePackageRepo.php
> +        $list_of_projects_cmd = "curl --header 'PRIVATE-TOKEN: $this->accessToken' '$this->gitlabApiPath/groups/$this->packageRepoGroup/projects?per_page=500' >> ./$this->comparisionFolder/$this->pro
@rakshithtb this is hard wired to Gitlabs, I'm going to merge to unblock testing, but create an Issue to abstract this as the library should allow other sources e.g. github, OR namespace the functions so it's clear these classes only are intended to support Gitlabs.

2021-06-02 11:17 UTC, garrowsmith commented on src/Package/ConfigInitializer.php
> +    protected $projectsPath = "projects.json";
@rakshithtb nitpick - I'd provide more descriptive information - what is this file, is it autogenerated?

2021-06-02 11:17 UTC, garrowsmith commented on src/Package/ConfigInitializer.php
> +     * Comparision Folder.
@rakshithtb typo... Comparision => Comparison. Please fix all instances :(

2021-06-02 11:17 UTC, garrowsmith commented on src/Package/ComparePackageRepo.php
> +    public function yamlDiffReport() {
@rakshithtb recommend splitting this up into logical functions as rationale is this allows us to more easily unit tests different stages, provide mocks. We want to allow test coverage due to the role this plays in the development process.

e.g.

yamlDiffReport()
* Generating list of projects
* Download report
* Invoke comparison logic

2021-06-04 10:33 UTC, guptahemant commented on src/Package/GitLab/ConfigInitializer.php
> +  protected $gitlabApiPath = "https://gitlab.bayer.com/api/v4";
This should be configurable, and not hard coded to bayer gitlab.

2021-06-04 12:20 UTC, garrowsmith commented on src/Package/GitLab/ComparePackageRepo.php
> +    // Create comparision folder.
Nitpick, one 'comparision' typo left, but I'm not blocking the MR @rakshithtb.

2021-06-07 04:26 UTC, rakshithtb commented
Closing this MR

2021-06-07 04:26 UTC, closed without merging